name: Automated Tests

on: [push]

jobs:

  rubocop:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.x
      - name: Install dependencies
        run: gem install rubocop
      - name: Run tests
        run: rubocop

  spec:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.5
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          git clone https://github.com/puppetlabs/puppetlabs-ruby_task_helper ../ruby_task_helper
      - name: Run tests
        run: bundle exec rake spec
